# 30 przykładowych pytań do testowania RAG
questions = [
    "Jaki jest cel projektu?",
    "Jakie są główne funkcje systemu?",
    "Kto jest autorem dokumentu?",
    "Jakie są wymagania techniczne?",
    "Jakie są zalety rozwiązania?",
    "Jakie są wady rozwiązania?",
    "Jakie są kroki instalacji?",
    "Jakie są kroki konfiguracji?",
    "Jakie są przykłady użycia?",
    "Jakie są ograniczenia systemu?",
    "Jakie są rekomendacje?",
    "Jakie są najważniejsze cytaty?",
    "Jakie są źródła danych?",
    "Jakie są typy dokumentów?",
    "Jakie są formaty plików?",
    "Jakie są metody chunkowania?",
    "Jakie są modele embeddingów?",
    "Jak działa scoring?",
    "Jak działa similarity search?",
    "Jakie są testy integracyjne?",
    "Jakie są endpointy API?",
    "Jakie są przykłady zapytań?",
    "Jakie są przykłady odpowiedzi?",
    "Jakie są typy cytowań?",
    "Jakie są metadane chunków?",
    "Jakie są typy indeksów?",
    "Jakie są retry/backoff strategie?",
    "Jakie są batch size dla embeddingów?",
    "Jakie są limity top_k?",
    "Jakie są plany rozwoju?"
]
